# Generated by Django 5.2 on 2025-10-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='type_billet',
            field=models.CharField(choices=[('VIP', 'VIP'), ('PREMIUM', 'Premium'), ('SIMPLE', 'Simple')], default='SIMPLE', max_length=20),
        ),
    ]
